# This workflow will install plasmaag and run a test run

name: PlasMAAG Workflow Test

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    
    # Free up diskspace: https://carlosbecker.com/posts/github-actions-disk-space/
    - run: df -h
    - name: "node-cleanup"
      run: |
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
        sudo docker image prune --all --force
        sudo docker builder prune -a
    - run: df -h
    
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Set up Micromamba
      uses: mamba-org/setup-micromamba@v1
      with:
        micromamba-version: '1.3.1-0'
        environment-file: envs/PlasMAAG.yaml
        environment-name: plasmaag
        init-shell: bash
        cache-environment: true
        post-cleanup: 'all'

    - name: Download test data
      run: |
        wget -O input_data.tar.gz "https://zenodo.org/records/15263434/files/input_data.tar.gz?download=1"
        tar -xvf input_data.tar.gz
      shell: bash

    - name: Run PlasMAAG
      run: |
        cd input_data
        PlasMAAG --reads_and_assembly_dir read_and_assembly_file.txt --output test_run_PlasMAAG --threads 8 --vamb_arguments '-o C -e 200 -q 25 75 150 --seed 1'
      shell: micromamba-shell {0}

